### ISSUE TITLE
No IP found...

### ISSUE THREAD

**Issue by mikeguidry** [dukebarman/ghidra-builder#4]
Used instructions exactly and received this message:
FAILURE: Build failed with an exception.

* Where:
Script '/files/ghidra/gradle/support/ip.gradle' line: 125

* What went wrong:
Execution failed for task ':GhidraServer:ip'.
> No IP found for /files/ghidra/Ghidra/Features/GhidraServer/yajsw-stable-12.12.zip in module: /files/ghidra/Ghidra/Features/GhidraServer. Expression: (ip != null). Values: ip = null

**Comment by dukebarman** [comment]
Try to rebuild, plz. Suppose that some files don't download in a process of preparing environment

**Comment by dukebarman** [comment]
I think I've repaired this with last commit (the developers've changed building process). If you see this error again, re-open plz
